# fly.toml app configuration file generated for pong-demo on 2026-05-12T14:35:36-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pong-demo'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 500
    soft_limit = 200

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpus = 1
  memory_mb = 256
